### ISSUE TITLE
USDA is a friend of Animal Agriculture

### ISSUE THREAD

**Issue by jfagreg** [jufoan/research#3]
Sources Needed (SN)  Place the results of your research in a comment below.

Needed by  8/30/2017

I need a few bullet points, each with a source, to support the assertion that the USDA is a big friend of animal agriculture. The bullet points should reflect costly items of expenditure by the USDA on behalf of animal agriculture.

Here is a totally made up, not true, example response:

* The USDA provides 10 billion dollars in price supports for crops to feed farm animals, while only providing 10 million dollars in price supports for plants grown for human consumption. Source: (link goes here.)

* The USDA assists public schools with educational materials supporting the dairy industry. Source: (link goes here.)

* The USDA spends 8 million dollars a year on marketing campaigns to support the beef industry.  Source: (link goes here.)

**Comment by janeen-garrett** [comment]
I will take it.

**Comment by jfagreg** [comment]
Thanks, Jan.

**Comment by jfagreg** [comment]
There is a possibility that the assertion that the USDA is a big friend of animal ag is supported in their mission statement, statement of purpose,  Congressional mandate, or such.

**Comment by janeen-garrett** [comment]
You can find figures on how much the USDA spends on animal agriculture in a chart on this website:  
I was not able to paste the link into this box so I will send the info by email.

**Comment by jfagreg** [comment]
Jan,

I've pasted your email here, with the links.  I don't know why that didn't work for you.  Anyway, those are great sources!  Thank you!

From Jan:

Here are some references for the task that I volunteered for:
 
http://www.pcrm.org/health/reports/agriculture-and-health-policies-unhealthful-foods
 
http://www.pcrm.org/health/reports/agriculture-and-health-policies-ag-versus-health
 
https://www.usda.gov/sites/default/files/documents/USDA-Budget-Summary-2018.pdf
page 15.
 
You may be able to use the first two references for the other task that you have available – quotes from medical doctors.
 
I also read that surplus dairy (and probably meat as well) are shuttled to school lunch programs.

**Comment by janeen-garrett** [comment]
Don't know. I tried twice using word copy and paste functions.

**Comment by jfagreg** [comment]
For future reference, here are the bullet points I gleaned from Jan's links. These points are chosen to support the assertion that the USDA is a friend of animal agriculture. The source for all the points is the first link:
http://www.pcrm.org/health/reports/agriculture-and-health-policies-unhealthful-foods

-Of the $246 billion is subsidies to agriculture between 1995 and 2009, 63% supported crops directly grown for livestock feed, while only 20% supported grains for human consumption 

-Fresh fruits and vegetables—called specialty crops by the USDA—do not receive subsidies.

-Subsidies for dairy producers amounted to $4.8 billion from 1995 thru 2009.

-The USDA provided $3.5 billion between 1995 and 2009 for the Livestock Compensation program, livestock feed assistance, and livestock emergency assistance.

-In 2009, the USDA spent $793 million for beef, pork, poultry, eggs, and fish.

-In 2009, the USDA spent more than $623 million to buy dairy products, mostly cheese.

-The USDA administers programs to help producers market their products, such as the “Got Milk” campaign.

**Comment by jfagreg** [comment]
For future reference, here are the bullet points I gleaned from Jan's links. These points are chosen to support the assertion that the USDA is a friend of animal agriculture. The source for all the points is the first link:
http://www.pcrm.org/health/reports/agriculture-and-health-policies-unhealthful-foods

-Of the 246 billion is subsidies to agriculture between 1995 and 2009, 63% supported crops directly grown for livestock feed, while only 20% supported grains for human consumption 

-Fresh fruits and vegetables—called specialty crops by the USDA—do not receive subsidies.

-Subsidies for dairy producers amounted to $4.8 billion from 1995 thru 2009.

-The USDA provided $3.5 billion between 1995 and 2009 for the Livestock Compensation program, livestock feed assistance, and livestock emergency assistance.

-In 2009, the USDA spent $793 million for beef, pork, poultry, eggs, and fish.

-In 2009, the USDA spent more than $623 million to buy dairy product products, mostly cheese.

-The USDA administers programs to help producers market their products, such as the “Got Milk” campaign.

**Comment by jfagreg** [comment]
FYI, the article for this research item is already posted.  I will now go back and incorporate this information in the article, change the Meta in the outline tab to reflect Jan's contribution for research, and submit changes to the copy editor.

The detailed bullet points will only appear in the outline. The article will have a citation to the article.

**Comment by janeen-garrett** [comment]
I am glad I let you do the bullet points.  You did much better than I would have.

 

Put a $ before 246?

**Comment by jfagreg** [comment]
Closing the issue. It's done.
